
import Head from 'next/head';

export default function TermsConditions() {
  return (
    <>
      <Head>
        <title>Terms & Conditions | Fiber Internet Online</title>
        <meta name="description" content="Terms & Conditions for TIME Fibre Services" />
      </Head>
      <div className="min-h-screen bg-gray-50 py-12">
        <div className="container mx-auto px-4 max-w-4xl">
          <h1 className="text-4xl font-bold mb-8 text-center text-primary">TIME's GENERAL TERMS</h1>
          <div className="bg-white p-8 md:p-12 rounded-3xl shadow-xl border border-gray-200 text-gray-700 space-y-8">
          <p className="font-medium">
            BY SIGNING OR ACCEPTING THE SERVICE ORDER (IN THE MANNER AS WE HAVE DETERMINED), CUSTOMER IS DEEMED TO ACKNOWLEDGE AND AGREE TO BE BOUND BY ALL THESE TERMS AND CONDITIONS. THIS GENERAL TERMS APPLY TO ALL SERVICES SUBSCRIBED BY YOU (UNLESS OTHERWISE PRESCRIBED IN A SERVICE SCHEDULE), AND WITH THE APPLICABLE SERVICE SCHEDULE, SERVICE ORDER FORM, ORDER DETAIL FORM, TOGETHER FORMS THE ENTIRE AGREEMENT WITH TIME.
          </p>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">1. GENERAL</h2>
            <div className="space-y-4">
              <p><strong>1.1 Digitally Signing.</strong> In addition to the conventional method of indicating your acceptance of the Service Order or SAT Form or any other document required by TIME by signing a printed version thereof at the appropriate place, you may also do so by (i) clicking on the “I Accept” or “I Agree” button or similar indicators and/or marking the appropriate check box where so indicated in our website, (ii) using a stylus-pen to sign on a portable digital device (such as a tablet or other portal electronic device) your signature or (iii) such manner as we may prescribed at our website periodically. If the Customer is a legal entity, firm or proprietorship, unless you inform us otherwise, you are deemed to have represented that the individual indicating acceptance on your behalf is permitted by you to do so, and you are estopped from denying such representation.</p>
              <p><strong>1.2 Your Account.</strong> Upon acceptance of the completed Service Order or electronic order by TIME we will create an account, and assign an account number. This account number identifies you as our customer in our system and in all communications, correspondences and invoicing from us to you. You will have one account number with us and it will be used for all services subscribed by you and it identifies you as our customer. If you already have an account number assigned by us, no new account number will be assigned. A change of account number is not the issuance of a new and independent account identifier.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">2. THE SERVICE</h2>
            <div className="space-y-4">
              <p><strong>2.1</strong> The Service that you subscribed is as indicated or specified in the Service Order or Order Detail form and described in the applicable Service Schedule. The applicable Service Schedule contains terms that governs and are specific to that Service and does not apply to other services that may be subscribed. Different Service Schedules will apply to different Services that are subscribed. Each Service subscribed is a separate and independent contract between the Parties.</p>
              <p><strong>2.2</strong> Unless otherwise expressly agreed in writing or as specified in or modified by the applicable Service Schedule, these General Terms shall apply to and govern the rights and obligations of the Parties.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">3. PROVISION OF SERVICES</h2>
            <div className="space-y-4">
              <p><strong>3.1 Preconditions to Provisioning.</strong> After the Service Order is accepted by TIME and Customer has paid the required deposits, registration fee, one-time charge and any third party’s one-time charge that may be imposed pursuant to or specified in the Service Order or the Service Schedule and invoiced by TIME, TIME shall, subject to the terms in the applicable Service Schedule, carry out and complete the works to provision the Service by the CRD stated in the Service Order and perform the requisite SAT, subject to Clause 3.3 below.</p>
              <p><strong>3.2 Service Acceptance Test.</strong> The Customer shall carry out all necessary preparation and works (as specified in the applicable Service Schedule) and render all assistance and co-operation required by TIME to facilitate the service acceptance tests. Upon completion of the provisioning works in respect of a Service and subject to Clause 3.1, TIME shall carry out the SAT for each Service subscribed. Once the SAT is satisfactorily completed, TIME shall provide the SAT Form that (i) certifies that the Service is ready for Customer’s use, (ii) specifies the commission or activation date, and (iii) such other relevant particulars to the Customer. You are to sign and return the SAT Form to TIME or indicate your acceptance of the SAT no later than three (3) business days of its receipt, failing which you are deemed to be satisfied with the SAT and accept the Service and the service commencement date (“SCD”) of the Service, is deemed to be the commission or activation date as specified in the SAT Form.</p>
              <p><strong>3.3 CRD Revision.</strong> TIME may revise the CRD if the original CRD cannot be met due to circumstances beyond TIME’s control, TIME experiencing delays in performing its works or if you delay or do not perform your obligations as specified in the applicable Service Schedule. The applicable Service Schedule may specify additional grounds for the revision of the CRD whether by TIME or by you.</p>
            </div>
          </section>
          
          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">4. CUSTOMER’S RIGHT TO USE THE SERVICE</h2>
            <div className="space-y-4">
                <p><strong>4.1 General.</strong> Unless otherwise expressly agreed in writing or as specified in the applicable Service Schedule, Customer may only use the Service in accordance with Applicable Law and for its own use only, and is neither permitted to sell, resell, hire, lease (including sub-lease), licence (including sub-licence), rent, offer, provide or sub-provision the Service, the Service Equipment or any portion thereto whether for consideration or otherwise to any third party nor use the Service for any fraudulent, unlawful, illegal or improper purpose or in breach of any Applicable Laws and regulations (local and international), including tampering, altering, adjusting, removing, diverting or affecting the Service or the TIME Network.</p>
                <p><strong>4.2 Service Upgrade.</strong> Unless otherwise specified in the applicable Service Schedule, no alteration or modification of the Service, at any time during the Initial Service Term, which reduces or downgrades the Service is permitted. If the Customer requires any upgrade to the existing subscribed Service for capacity (“Service Upgrade”), TIME will provide a quotation together with revised or new terms for the Service Upgrade to the Customer. If the Customer agrees to the said revised or new terms, the Parties shall execute a new Service Order Form to reflect the said revised or new terms and Charges for the Service Upgrade. The Service Upgrade shall commence on the date as stipulated in the new Service Order Form. Notwithstanding anything to the contrary to the Service Schedule or these terms:
                <br/>(a) the Initial Service Term of the Qualifying Service will be automatically extended so that the expiry date of the Service Upgrade and the Qualifying Service are the same; and
                <br/>(b) the Charges for the Qualifying Service shall remain unchanged during the said extension of the Initial Service Term in Clause 4.2(a) above save where otherwise agreed in writing between the Parties.</p>
                <p><strong>4.3 Additional Services.</strong> The Customer may subscribe for additional Services (including but not limited to Managed Service or value-added service) in addition to the existing Services subscribed by the Customer at any time. If the Customer requires any additional Service to the existing subscribed Service, TIME will provide a quotation together with revised or new terms for the additional Service to the Customer. If the Customer agrees to the said revised or new terms, the Parties shall execute a new Service Order Form to reflect the said revised or new terms and Charges for the additional Service. If the additional Service subscribed by you is to commence on a date after the SCD of the Qualifying Service, the additional Service will commence on the date notified by TIME or the date stipulated in the new Service Order Form. Notwithstanding anything to the contrary in this Service Schedule or the General Terms, the Initial Service Term of the Qualifying Service will be automatically extended so that the expiry date of the additional Service and the Qualifying Service are the same.</p>
                <p><strong>4.4 Service Monitoring.</strong> The Service is subject to lawful intercept and/or monitoring as may be required by the country’s regulatory and law enforcement agencies where the Service Location(s) is at pursuant to the Applicable Law, and TIME will have to ensure that such requirements are in full compliance according to the Applicable Law, and Customer hereby consents to such lawful intercept and/or monitoring activities.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">5. INITIAL SERVICE TERM & RENEWALS</h2>
            <div className="space-y-4">
                <p><strong>5.1 Term of Service Order.</strong> This Service Order shall commence on the date of stated in the Service Order and shall be subsisting unless otherwise terminated by either Party in accordance with the terms of this Service Order.</p>
                <p><strong>5.2 Initial Service Term.</strong> The Customer agrees that the Initial Service Term for each Service subscribed by the Customer is as specified in the Service Order (or in the applicable Service Schedule) which starts from the SCD, subject always to Clauses 4.2 and 4.3 above.</p>
                <p><strong>5.3 Renewals.</strong> Save where otherwise provided in the applicable Service Schedule and/or unless the Customer notifies TIME in writing at least ninety (90) days before the expiry of the Initial Service Term, that the Initial Service Term is not to be renewed, the Service shall be automatically renewed for the period:
                <br/>(a) as stipulated in a new Service Order Form which the Customer has executed for renewal of the existing Service; or
                <br/>(b) equal to the Initial Service Term where the Customer does not or has yet to execute a new Service Order Form for renewal of the existing Service,
                <br/>commencing on the day after the expiry of the Initial Service Term on the terms in this General Terms.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">6. CHARGES, INVOICING & PAYMENT</h2>
            <div className="space-y-4">
                <p><strong>6.1 Scope of Charges.</strong> Unless otherwise specified in the applicable plan, Service Order or Service Schedule, the charges may include a registration fee, deposit, one-time charge, MRC and third party service and/or recurring charges (“Charges”) which are as indicated and detailed in the Service Order. All Charges exclude applicable VAT, SST or any other form of consumption taxes (as may be imposed by law from time to time) in respect of the provision of taxable service by a taxable person (as a service provider) to a customer (other than income or corporate taxes). If any withholding tax is applicable to a Customer making payment to TIME for the Service, then the Customer shall gross up the Charges such that TIME receives the full Charges net of withholding tax.</p>
                <p><strong>6.2 Deposits.</strong> If you are required to pay a deposit to us (as may be specified in the applicable plan, Service Schedule or the Service Order) and it is not expressly waived, then the following conditions shall be applicable:
                <ul className="list-disc pl-5 mt-2 space-y-1">
                    <li>(a) The deposit paid by you is as security for the due observance and performance by you of the provisions of the Agreement.</li>
                    <li>(b) The deposit amount shall be maintained at such sum as may be specified in the Service Order (and in default as specified in the applicable Service Schedule) for so long as you continue to subscribe for the Service.</li>
                    <li>(c) The deposit shall not, without our prior written consent, be deemed to be or treated as payment of the Charges.</li>
                    <li>(d) No increase in the deposit is required if the Charges are increased, unless otherwise specified in the applicable Service Schedule.</li>
                    <li>(e) We may set off the deposit against any invoices issued and/or Charges due from you. If the deposit is set off by us and the Agreement is not terminated, you shall pay a further sum as deposit of such amount as may be notified by us.</li>
                    <li>(f) We shall process the refund of your deposit and excess payment within ninety (90) days from the date of expiry, termination or cessation of the Service, after deducting any unpaid invoices, outstanding Charges, Balance Charges, Cancellation Costs (if applicable) and/or Termination Charges (if applicable) due from the you to us under the Agreement free from any interest.</li>
                    <li>(g) All refunds will be through telegraphic transfer at your indicated bank account, save for Time Home Broadband Services where any refund shall only be to your Malaysian bank account. However, if you fail to provide us with the details of your bank account within the duration as specified in Clause 6.2(f) above, and after making reasonable attempts to refund the amount, then we shall be at liberty to either retain such refunds after a lapse of twelve (12) months, and you are deemed to have consented to the same or deposit the same with the relevant authority designated under the Malaysian Unclaimed Moneys Act 1965.</li>
                </ul>
                </p>
                <p><strong>6.3 Miscellaneous Fees:</strong> Customer agrees to pay the following fees (a) a printed bill fee of RM5.00 per bill (if Customer so indicates in the Service Order that it prefers to receive a printed bill as opposed to a digital bill that is sent via email); and (b) such other fees that may be imposed such as a re-connection fee for suspended service due to fault of the Customer, but such other fees will be specified in our website, applicable Service Schedule or in the Service Order from time to time. If no such fees are specified then no such fees are payable.</p>
                <p><strong>6.4 Invoicing.</strong> TIME shall issue a tax invoice to the Customer for the Charges and the Customer shall pay and continue to pay the Charges by the due date stated in the invoices. Notwithstanding anything to the contrary, the Customer acknowledges and agrees that its obligation to pay all Charges due and payable shall not be waived, absolved or diminished by virtue of its failure or neglect to check, enquire, understand and ascertain the nature of Services subscribed or used by the Customer and the applicable charges associated with such Services, and you further acknowledge that it shall be your responsibility to request from TIME the invoices it has not received for any given billing period. If the Customer fails to pay the invoice by its due date, TIME may impose a late payment charge for such unpaid invoices at the rate not exceeding 18% per annum calculated on a monthly rest from the due date until full settlement. It is Customer’s responsibility to request for invoices from TIME that it has not received. The Customer shall be responsible for all reasonable costs incurred by TIME in the collection of any overdue amount.</p>
                <p><strong>6.5 Auto-Debit Payment Service.</strong> If the APS is available to you, and you indicate that you wish to subscribe for the APS, then the terms set out in the Auto-Debit Payment Schedule which is available at our website, shall be applicable in addition to these General Terms.</p>
                <p><strong>6.6 Billing Cycle.</strong> On or after the SCD, TIME may invoice the Customer for the periodic recurring charges according to the applicable billing cycle in the Service Order.</p>
                <p><strong>6.7 Bank Charges.</strong> All payments made to TIME shall be free and clear from all bank and service charges, and without deduction, set off or counter claim and the full invoiced amount is to be received by TIME in discharge of Customer’s payment obligations.</p>
                <p><strong>6.8 Invoice Dispute.</strong> Unless otherwise specified in the applicable Service Schedule, all bona fide disputes concerning an invoice are to be raised in writing by Customer within thirty (30) days of the date in the invoice identified as “statement date”, and shall specify the amount disputed, the reasons for disputing the amount and provide documentary records supporting the reasons. Customer shall pay all amounts in an invoice which are not in dispute by the due date. Upon receipt of the dispute, TIME shall promptly investigate the dispute, and either issue a revised invoice if the dispute is justified or not. If a revised invoice is issued, Customer shall pay the revised invoice within fourteen (14) days. If a revised invoice is not issued, the Parties shall promptly resolve the dispute in good faith.</p>
                <p><strong>6.9 MRC on Renewal.</strong> Save where otherwise provided in the Service Schedule, the following are the terms applicable to revising the MRC for Service or Service Equipment (where applicable) where there are no changes in the requirements in any form or manner on the renewal of the Initial Service Term:
                <br/>(a) On the start date of the Renewed Service Term, the MRC may be revised by TIME (the “Adjusted Recurring Charge”) unless otherwise agreed in writing between the Parties; and
                <br/>(b) The Adjusted Recurring Charge shall commence from the start date of the Renewed Service Term and apply until the expiry of the Renewed Service Term.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">7. SERVICE INTERRUPTIONS & SUSPENSION</h2>
            <div className="space-y-4">
               <p><strong>7.1 Interruption.</strong> TIME does not warrant that the Service is error-free, provided without interruption or fault. Further, if (a) for emergency, operational or it is technically necessary to do so; (b) a Force Majeure Event occurs; (c) a disruption occurs due to acts of third parties (e.g. fibre cuts, DDOS attacks etc.), then the Service may be interrupted. If you are aware, you ought to notify TIME of such interruption; and if we are aware we shall notify you of the same via our website. TIME shall restore the affected Services as soon as reasonably practicable upon the cessation of the above events.</p>
               <p><strong>7.2 Suspension.</strong> If
               <ul className="list-disc pl-5 mt-2 space-y-1">
                 <li>(a) Charges or any invoice remains unpaid or outstanding for this or any other Services that are subscribed by you (including if you withhold any payments, persistently or repeatedly fails to make payment on the due date of the invoices);</li>
                 <li>(b) a Service Location is to be vacated;</li>
                 <li>(c) a Force Majeure Event occurs;</li>
                 <li>(d) Clause 7.1(a) or (c) applies;</li>
                 <li>(e) your use of the Service is not in accordance with Applicable Laws;</li>
                 <li>(f) you are in breach of our obligations specified in the General Terms and/or the Service Schedules;</li>
                 <li>(g) TIME is requested or directed by SKMM or any relevant authority to suspend the Service;</li>
                 <li>(h) Customer’s IP address is under a distributed denial of service attack directed towards the Customer’s IP address or addresses connected to TIME’ Network that, in TIME’ reasonable judgment, causes TIME to believe that the Customer’s network may be compromised by being inundated with nefarious or bogus data traffic, thereby denying service to the Customer’s systems connected to TIME’s Network; or</li>
                 <li>(i) TIME notifies the Customer to disconnect and replace Customer Equipment because it is neither type approved or agreed to by TIME, and the Customer fails, neglects or refuses to do so after fourteen (14) days from date of receipt of written notice from TIME,</li>
               </ul>
               then TIME may suspend a Service either after notifying the Customer at least five (5) days before doing so, except in cases of (c) to (h) above, where TIME will try to give at least twenty four (24) hours verbal prior notice to Customer or in the case of (i) above, after the expiry of the fourteen (14) days period, as the case may be. TIME may reconnect a suspended Service once the event ceases or in the case of (i) above, until the Customer Equipment is type approved or TIME’s agreement (which agreement is not unreasonably delayed or conditioned) is obtained.</p>
               <p><strong>7.3 Liability to pay invoices.</strong> Notwithstanding Clause 7.1 or 7.2 above, you shall remain liable to pay to TIME all applicable Charges during the period of interruption, suspension or loss of Service(s) or any part thereof.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">8. TERMINATION</h2>
            <div className="space-y-4">
                <p><strong>8.1 Termination by Customer.</strong> Customer may immediately terminate the Service or the Agreement if (a) TIME is in breach of its obligations herein and/or under the Service Schedule; and (b) the Customer has issued a notice requiring TIME to remedy the same within thirty (30) days and TIME has failed, neglected or refused to do so. Notwithstanding the above, if the Customer has subscribed for different Services, the Customer cannot terminate a Service whilst continuing to subscribe for the remaining Services.</p>
                <p><strong>8.2 Termination for convenience.</strong> If the Customer terminates this Agreement after the SCD and before the expiry of the Initial Service Term, or the expiry of the Renewed Service Term, as the case may be, then the Customer shall give TIME thirty (30) days prior notice in writing before the date of such termination.</p>
                <p><strong>8.3 Termination by either Party.</strong> Either Party may terminate this Agreement immediately in writing if (a) an order is made or an effective resolution is passed for the winding up, dissolution or bankruptcy of the other Party, or for the reconstruction and amalgamation of the other Party otherwise than pursuant to section 366 of the Malaysian Companies Act 2016 or similar proceedings under any Applicable Law; (b) a receiver, receiver and manager, judicial manager, provisional liquidator, liquidator, trustee in bankruptcy or like official is appointed over the whole or substantially the whole of the undertaking of the other Party; (c) the other Party shall make any arrangement for the benefit of or enter into any arrangement or composition agreement with its creditors; (d) a holder of an encumbrance takes possession of the whole or substantially the whole of the property of the other Party; (e) execution is levied against the assets or undertaking of the other Party; and a claim may be made accordingly or (f) the other Party shall have infringed or violated any Applicable Law pertaining to the use of the Services and such Party has failed, neglected or refused to remedy such an infringement or violation within the time frame stipulated by the relevant authority.</p>
                <p><strong>8.4 Termination by TIME.</strong> Without prejudice to any other right or remedy, TIME may immediately terminate this Agreement if either (a) after the expiry of fourteen (14) days of a demand for payment by TIME for any outstanding invoices or Charges in arrears has been issued, and the Customer has not paid the sum demanded; (b) Customer is in breach of its obligations or any term in this General Terms (other than Clause 4.1 General Terms) and has not remedied the same to the reasonable satisfaction of TIME; (c) after the SCD, the Customer is in default of any of its obligations or in breach of the applicable provisions as set out in this General Terms (other than Clause 4.1 General Terms) or the applicable Service Schedule, and the Customer has failed, neglected or refused to remedy such defaults after receipt of a notice from TIME to do so by the date specified in such notice; (d) Customer has breached any agreement it may have entered into with an Affiliate and has failed to rectify and remedy such breach to the reasonable satisfaction of that Affiliate; (e) TIME is in receipt of a direction, order or notice issued by an appropriate authority (being SKMM, PDRM, MACC or the Government of Malaysia, as the case may be) either requiring TIME to terminate the provision of the Service to the Customer, suspend the Service or declaring that the use of the Service is contrary to the Applicable Law; (f) the Customer shall infringe or violate the Applicable Law pertaining to the use of the Service and has failed, neglected and/or refused to remedy the infringement or violation within the time frame stipulated by the relevant authority; or (g) if the Customer is in breach of Clause 4.1 General Terms.</p>
                <p><strong>8.5 Termination for Force Majeure.</strong> If a Force Majeure Event occurs and continues for thirty (30) continuous days, then either Party may in writing terminate the Service Order without any liability to each other, save for antecedent breaches and neither Party shall be liable for any breach, failure or delay in performance of its obligations pursuant to or of these terms (excluding Customer’s payment obligations), death or personal injury suffered.</p>
                <p><strong>8.6 Termination Notices to be in writing.</strong> Unless otherwise specified in the applicable Service Schedule, all notices of termination under this Clause 8 must be in writing, on a Party’s letterhead and signed by the authorised officer and sent to the other Party, and a copy of which may be sent via electronic mail containing the scanned letter as an attachment.</p>
                <p><strong>8.7 Consequences of Termination</strong>
                <ul className="list-disc pl-5 mt-2 space-y-1">
                  <li>(a) If Customer terminates this Agreement pursuant to Clause 8.2 General Terms or if TIME terminates this Agreement pursuant to Clause 8.3 or 8.4 General Terms or pursuant to any other provision in the applicable Service Schedule that grants TIME a specific right to terminate due to a breach by the Customer, then Customer shall pay TIME the Balance Charges, the Termination Charges and all Charges in arrears up to the date of termination, unless otherwise specified in the applicable Service Schedule.</li>
                  <li>(b) If Customer terminates this Agreement pursuant to Clause 8.1 or 8.3 General Terms or pursuant any specific provision in the applicable Service Schedule that grant the Customer a specific right to terminate due to a breach by TIME, neither the Balance Charges nor the Termination Charges shall be payable to TIME but the Customer will pay any Charges that are in arrears up to the date of termination.</li>
                  <li>(c) If the Agreement is terminated due to a Force Majeure Event pursuant to Clause 8.5 General Terms, then neither the Balance Charges nor the Termination Charges shall be payable by Customer but the Customer shall pay any Charges that are in arrears up to the date of termination and TIME shall not be liable to the Customer for any losses, damages or expenses suffered.</li>
                  <li>(d) Regardless of the Party terminating the Agreement, the Service shall cease to be provided by TIME on the date of termination.</li>
                  <li>(e) In all cases, the Customer shall reimburse TIME for all third party charges, costs and expenses that are imposed on TIME by such third party in order for TIME to either provide the Service and/or to terminate the service provided by such third parties.</li>
                </ul>
                </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">9. LIMITATION OF LIABILITY AND INDEMNITY</h2>
            <div className="space-y-4">
                <p><strong>9.1 Direct Losses.</strong> Save where prohibited by Applicable Laws and due to the negligence, wilful default or misconduct of a Party and/or unless otherwise specified in the applicable Service Schedule, the liability of each Party to the other Party for all damages, losses, costs or expenses arising out of, in connection with or related to the Service Order, regardless of the legal principle that imposes such liability, whether in contract, equity, intended conduct, tort or otherwise, will be limited to and will not exceed, (in the aggregate for all claims, actions and causes of action of every kind and nature), an amount equal to the aggregate value of the monthly recurring charges payable to TIME (excluding any third party recurring charges) for a twelve (12) months period. This limit does not apply to any Charges owed by the Customer to TIME (including Termination Charges or Cancellation Costs), recovery of the Balance Charges and/or any third party recurring charges incurred in order to provide the Service.</p>
                <p><strong>9.2 Indirect Damages.</strong> Neither Party shall be liable to the other Party under this Service Order for loss of production, loss of profit, loss of use, loss of business or market share, loss of data, revenue or any other economic loss, whether direct or indirect, or for any indirect, incidental, consequential, aggravated or exemplary damages, whether or not the possibility of such damages could have been reasonably foreseen.</p>
                <p><strong>9.3 Exclusion of Liability.</strong> Unless otherwise specified in the applicable Service Schedule, TIME shall neither be responsible for any third party services or products which you access, use or acquire (whether by yourself or by TIME acting on your behalf) together with the Service, for any loss or damage caused or contributed by such services or products to the Customer nor for any losses suffered by you due to any Service interruption or suspension.</p>
                <p><strong>9.4 Indemnity.</strong> The Customer shall indemnify and hold TIME harmless against any and all loss, liability, cost, expense or claim (including reasonable legal expenses) suffered or incurred by TIME arising directly or indirectly from or in connection with :-
                <ul className="list-disc pl-5 mt-2 space-y-1">
                    <li>(a) any failure by the Customer to comply with any of the provisions of this Service Order and/or the Service Schedules, such other rules, regulations and policies as specified in this Service Order and/or the Service Schedules, third party service providers terms of services, any instructions, notices or directions issued by TIME and/or any appropriate authorities or any Applicable Law in force;</li>
                    <li>(b) any claims for libel, infringement of intellectual property rights or breach of any Applicable Laws whatsoever arising from or attributable to any material transmitted, received or stored via the Services and from all claims arising out of any act or omission of the Customer or any unauthorized use of the Services;</li>
                    <li>(c) any damage to TIME property, any damage to any property (including third party’s property) or personal injury (including death) attributable to the Customer’s Equipment, Customer’s material and/or any act or omission of the Customer and of any person under its control or acting under its authority; or</li>
                    <li>(d) any and all claims, demands, proceedings or fines made or imposed against TIME by a third party arising out of, in connection with or due to the Customer’s breach of these terms or in using the Services, including claims for defamation, infringement of intellectual property rights, death or personal injury and/or property damage.</li>
                </ul>
                </p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">10. NOTICES</h2>
            <div className="space-y-4">
                <p><strong>10.1</strong> You consent to the delivery and/or service of any notice, invoice, statement or other communication hereunder by electronic mail, hand, courier and/or by prepaid ordinary post to your address as set out in the Service Order or to your last known address in our records.</p>
                <p><strong>10.2</strong> Notices, demands or other communications shall be deemed effective if (a) by electronic mail, on the day immediately after successful transmission; (b) hand delivery, on the day of delivery; (c) by prepaid ordinary post, five (5) business days after despatch; (d) by courier, one (1) business day after despatch; (e) by facsimile, on the day of transmission provided that the transmission report from the sender’s facsimile machine confirms that transmission is in full and without error. If receipt is on a day, which is not a business day, then receipt shall be deemed to occur on the next immediate business day.</p>
                <p><strong>10.3</strong> You agree that in the event that any action is initiated in the courts in Malaysia in respect of this Agreement, the legal process and other documents may be served by posting the documents to you by registered post at the address set out in this Service Order or to your last known address in our records and such service shall, on the fifth (5) day after posting, be deemed to be good and sufficient service of such legal process or documents.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">11. MISCELLANEOUS.</h2>
            <div className="space-y-4">
                <p><strong>11.1 Changes in Law.</strong> Should a new law or an amendment to an existing law occur that impacts this Service Order or the Service, then notwithstanding anything contained herein, the clauses herein shall be deemed to be amended to such an extent as is necessary to enable Parties to comply with such laws.</p>
                <p><strong>11.2 Anti-Bribery and Corruption.</strong>
                <br/><strong>11.2.1 The Customer agrees that:</strong>
                <ul className="list-disc pl-5 mt-2 space-y-1">
                    <li>(a) it shall strictly comply with all laws and regulations relating to anti-bribery and corruption including but not limited to the Malaysian Anti-Corruption Commission Act 2009 (“Anti-Bribery and Corruption Laws”);</li>
                    <li>(b) it has read, understood and agreed at all times during the term of this Service Order to comply with TIME Group Principles Anti-Bribery & Corruption Policy which can be viewed at <a href="https://www.time.com.my/general/abc-policy" target="_blank" className="text-primary hover:underline">https://www.time.com.my/general/abc-policy</a> (“TIME Group Principles Anti-Bribery & Corruption Policy”) and detailed provisions relating to anti-bribery and corruption and shall form an integral part of this Service Order;</li>
                    <li>(c) it shall inform and undertake that all its employees, representatives, personnel, subcontractors, consultants and agent(s) (“Representatives”) who will work on this Service Order comply with the requirements of TIME’s Business Integrity & Anti-Corruption Policy; and</li>
                    <li>(d) it shall take all measures to prevent corrupt practices, unfair means and illegal activities at all times throughout the term of this Service Order including maintaining accurate books, records and accounts related to its activities and internal controls.</li>
                </ul>
                <br/><strong>11.2.2</strong> The Customer agrees that any non-compliance with Anti-Bribery and Corruption Laws or TIME Group Principles Anti-Bribery & Corruption Policy is a ground for TIME to forthwith terminate the Service Order.
                <br/><strong>11.2.3</strong> The Customer agrees to indemnify and hold harmless TIME in respect to any claims made against TIME arising out of any breach by it and/or its Representatives of any provision of this clause or any non-compliance with Anti-Bribery and Corruption Laws and/or TIME Group Principles Anti-Bribery & Corruption Policy.</p>
                <p><strong>11.3 Conclusive Evidence.</strong> The Parties agree that a certificate of indebtedness issued by the TIME officer in charge of finance shall be binding evidence as to the amount due and owing by Customer to TIME and is conclusive in any legal proceedings, save for manifest errors or omissions.</p>
                <p><strong>11.4 Representation.</strong> You represent and warrant that all information required and furnished by you to TIME in connection with the Service and in the Service Order are correct and accurate in every material respect and are not false, misleading, deceptive, defamatory and/or unlawful. Nothing herein or the applicable Service Schedule shall imply any obligation on the part of TIME to verify the accuracy and authenticity of such information. Additionally you and TIME represent and warrant to each other that (a) each Party has the necessary capacity, authority, rights, licences and permissions to enter into and perform its obligations under this Agreement; and (b) the Service Order together with the General Terms and the applicable Service Schedule is a valid and enforceable agreement against a Party, notwithstanding any defect, deficiency or omission. Further TIME does not make any representations or warranty, whether express or implied, and excludes any implied warranties (whether arising by operation of Applicable Law, equity or common law) that the Service will achieve the expected functionality, will be error-free or uninterrupted, and/or is of a specified or of any quality.</p>
                <p><strong>11.5 Variations of Terms.</strong> Unless otherwise prescribed in this General Terms or a Service Schedule, TIME may amend, vary, modify, add or delete (“Variation”) these General Terms and/or Service Schedules from time to time by publishing and making available the revised General Terms and/or Service Schedules on TIME’s website at <a href="http://www.time.com.my" target="_blank" className="text-primary hover:underline">www.time.com.my</a> with notice to the Customers by way of highlighting to the Customers on TIME’s website at <a href="http://www.time.com.my" target="_blank" className="text-primary hover:underline">www.time.com.my</a> of updates to the General Terms or Services Schedules; or where reasonable, by sending the Customer an updated version of these General Terms or the applicable updated Service Schedule. Where a Customer uses and/or continues to use the Services after the date on which such Variation comes into effect, such use shall be deemed acceptance of such Variation by Customer.</p>
                <p><strong>11.6 Waiver.</strong> Only a written waiver of any breach, right or remedy is only effective if it is duly signed by the Party granting the waiver. Any failure or delay of a Party to exercise or enforce (including any partial exercise or enforcement of) any provision contained herein and/or any other indulgence given by that Party shall not be deemed as a waiver by that Party of its right, power, authority, discretion, remedy or right of action against the other Party in respect of any breach by the other Party of its obligations hereunder.</p>
                <p><strong>11.7 Recovery of Legal Costs.</strong> In any legal proceedings commenced by TIME against you as result of your failure to pay or your breach or default under the Agreement or in connection with indemnification as stipulated under Clause 9.4 General Terms, all legal costs and expense incurred by TIME shall be recoverable from you on a solicitor-client basis.</p>
                <p><strong>11.8 Entire Agreement.</strong> Unless otherwise provided in the ESA where applicable, this General Terms and for each Service that you have subscribed from us, the applicable Service Schedule and the Service Order shall together form the entire Agreement between the Parties.</p>
                <p><strong>11.9 Stamp Duty.</strong> Customer shall bear the applicable stamp duty and any penalties that may be imposed by the Government of Malaysia, unless otherwise agreed by TIME in writing.</p>
                <p><strong>11.10 Use of Proprietary Symbols:</strong> Each Party undertakes not to use the logos, trade and service marks, trade dress or other proprietary identifying symbols of the other Party whether n any press release, public statement, advertising, signage, marketing materials, brochures or other materials in any medium or otherwise unless the other Party shall have first given its written consent thereto which consent shall not be unreasonably withheld.</p>
                <p><strong>11.11 Assignment.</strong> The Customer shall not assign any rights, interest, remedies and obligations herein without the prior written consent of TIME, whose consent may be withheld at its sole and absolute discretion. TIME shall be entitled to assign, novate or transfer this Agreement or any of its right and remedies hereunder to any Affiliate without the consent of the Customer PROVIDED ALWAYS that TIME shall provide the Customer with a written notice of such assignment, novation or transfer. Nothing contained herein shall be deemed to confer any rights upon or be enforceable by any person other than the Parties hereto.</p>
                <p><strong>11.12 Severability.</strong> In the event any provision of this Agreement is held by a court of competent jurisdiction to be contrary to the law, the remaining provisions of this Agreement will remain in full force and effect.</p>
                <p><strong>11.13 Binding Effect:</strong> This Agreement shall be binding upon the permitted assigns and successors-in-title of the Parties hereto. It is further provided that this Agreement shall not be discharged or in any way affected by any change in the composition or identity of the Parties hereto by amalgamation, reconstruction or otherwise.</p>
                <p><strong>11.14 Cloud Network Infrastructure.</strong> TIME shall use its best efforts to ensure that the appropriate measures are taken to safeguard the security of its customer’s data in its cloud network infrastructure in accordance to Malaysia laws and regulations.</p>
                <p><strong>11.15 Governing Law & Jurisdiction.</strong> The Service Order shall be governed by and construed in all respects in accordance with the Laws of Malaysia and if Parties is unable to resolve any dispute under Clause 12 below, then Parties hereto shall submit to the jurisdiction of the Courts of Malaysia.</p>
                <p><strong>11.16 Compliance with Laws.</strong> Parties shall comply with all Applicable Laws in force in Malaysia and shall keep the other Party indemnified against all penalties and liabilities of every kind for such breach of any such written law.</p>
                <p><strong>11.17 Personal Data and Data Protection.</strong> The Parties agree to comply with all applicable legislations and regulations relating to privacy and/or data protection, including without limitation to the Malaysian Personal Data Protection Act 2010 (Act 709). The Customer must comply with our Privacy Policy and all legal requirements and standards applicable to data protection and privacy, as amended, revised, and/or supplemented from time to time. Time’s Privacy Policy can be viewed at <a href="https://www.time.com.my/privacy-policy" target="_blank" className="text-primary hover:underline">https://www.time.com.my/privacy-policy</a> (“Privacy Policy”).</p>
                <p><strong>11.18 Confidentiality.</strong> All information and documentation provided by TIME to the Customer (“Confidential Information”) is proprietary and confidential to TIME and shall be kept as confidential by the Customer at all times. The Customer shall not at any time, during or after the expiry or termination of the Service Order, disclose any Confidential Information whether directly or indirectly to any third party without the prior written consent of TIME.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">12. DISPUTE RESOLUTION</h2>
            <div className="space-y-4">
               <p>In the event of any dispute or difference arising out of, in connection with, or in relation to the Agreement between the Parties (“Dispute”), then as soon as reasonably possible upon the written request of either Party, each of the Parties will meet to resolve the dispute. The designated representatives of each Party will meet as often as the Parties reasonably deem necessary in order to gather and furnish to the other all information with respect to the Dispute. The representatives will discuss the Dispute and will negotiate in good faith in an effort to resolve the Dispute without the necessity of any formal proceedings. However, should Parties fail to amicably resolve the Dispute within ninety (90) days from the date of the written request on the Dispute in question, either Party may then elect to pursue the Dispute in the dispute forum stipulated in Clause 11.15 General Terms.</p>
            </div>
          </section>

          <section>
            <h2 className="text-2xl font-bold text-gray-900 mb-4">13. DEFINITIONS & INTERPRETATIONS</h2>
            <div className="space-y-4">
                <p><strong>13.1 Definitions.</strong> The following words and phrases have the prescribed meanings, unless the context otherwise requires, and shall apply to the General Terms and each of the Service Schedules.</p>
                <ul className="list-disc pl-5 mt-2 space-y-2 text-sm">
                    <li>(a) “Access Line” means the terrestrial connectivity from the Service Location to TIME Network;</li>
                    <li>(b) “Affiliate” means either a subsidiary of the parent company of TIME, a subsidiary of such a subsidiary, another subsidiary of the parent company of TIME or an associate company of such subsidiary, a subsidiary or associate of TIME;</li>
                    <li>(c) “Agreement” means the Service Order or electronic, digital or online order, order detail form, the General Terms, the applicable Service Schedule and if applicable, the auto-debit payment schedule, unless otherwise defined in the ESA where applicable;</li>
                    <li>(d) “APS” means the auto-debit payment service, as defined in the auto-debit payment schedule;</li>
                    <li>(e) “Applicable Law” means the applicable constitution, law, statute, enactment, ordinance, code, by-law, rule, regulation, order, judgment or decree of any government, state or political subdivision thereof, courts, regulator or semi-regulatory or administrative body;</li>
                    <li>(f) “Balance Charges” means the applicable recurring Charges (ascertained as a monthly charge basis) multiplied by the unexpired balance of the Initial Service Term or the Renewed Service Term, as the case may be (expressed in months);</li>
                    <li>(g) “Cancellation Cost” or “Cancellation Charges” means those costs identified in the Service Schedule applicable to a Service that is payable if that Service is cancelled before the SCD, CRD or such other date as set out in the applicable Service Schedule;</li>
                    <li>(h) “CRD” means the date requested by you for the Service to be available for your use;</li>
                    <li>(i) “CSP” means cloud service provider, being a third party that operates and provides services to customers via a cloud platform;</li>
                    <li>(j) “Customer Equipment” or “CPE” has the meaning as specified in the applicable Service Schedule;</li>
                    <li>(k) “Customer”, “you” or “your” means the customer whose particulars or details are identified in the section referred to as either “Applicant Information”, “Customer Information” or “Customer Details” in our Service Order Form, online subscription portal or sign-up application;</li>
                    <li>(l) “Eligible Service” means only those service types that are more particularly identified in the applicable Service Schedule, and listed as an eligible service in the applicable Service Schedule and not any other service type, which will be eligible for the service level guarantee provided by TIME;</li>
                    <li>(m) “ESA” means the enterprise service agreement entered into between TIME and the Customer for the provision of a specific Service;</li>
                    <li>(n) “Extra Charges” mean either a one-off or recurring charge that may be levied on Customer for matters specified in the applicable Service Schedule which are in addition to the Charges;</li>
                    <li>(o) “Force Majeure Event” means (i) rebellion, civil unrest, riot, acts of terrorism, declaration of war, national emergencies, national disasters, strikes, lock-outs, fire, explosion, acts of God, adverse inclement weather, lightning-strikes, natural disasters, earthquakes, diseases, epidemics, pandemics, quarantines, government lockdowns, public health movement restriction order, damage to or destruction of TIME’s network (whether due to acts of animals, third parties or otherwise), including interference to or compromise of TIME’s network caused by third party actions (e.g. DDOS attacks), occurrence of a major power disruption, interruption to supply chain that is beyond the reasonable control of TIME, commercial power failure, disruption of interconnected communications facilities or networks, acts by Government, regulatory bodies, national councils, local authorities or other appropriate authorities or any other event which is beyond the reasonable control of TIME; and (ii) which materially affects the provision of the Service;</li>
                    <li>(p) “Incident” means an unplanned interruption to, or a reduction in the network availability of an Eligible Service;</li>
                    <li>(q) “Initial Service Term” means the minimum contract or service period that the Service is subscribed by you and to be provided by TIME as specified in the Service Order or as may be specified in the applicable Service Schedule;</li>
                    <li>(r) “Local Contracted Business Hours” mean the business hours of the OLNO in the country where the IPLC or IEPL service is provided to the Customer;</li>
                    <li>(s) “MACC” means the Malaysian Anti-Corruption Commission, established under the Malaysian Anti-Corruption Commission Act 2009;</li>
                    <li>(t) “Managed Service” means the type of managed services that is offered by TIME as identified in Service Schedule G and Service Schedule H;</li>
                    <li>(u) “MRC” or “Monthly Recurring Charge” means either the monthly recurring charge or if the recurring charge is stated other 
than on a per month basis, to divide the recurring charge by the requisite number of months to derive the per month recurring charge. As an example, if the recurring charge of RM3000 is on a quarterly basis, then the per month recurring charge is RM3,000 divided by 3;</li>
                    <li>(v) “OLNO” means a third party network operator (including an Affiliate) that is licensed in the country (other than Malaysia) where the Service Location is at;</li>
                    <li>(w) “PDRM” means the Royal Malaysian Police, being the law enforcement agency in Malaysia;</li>
                    <li>(x) “Permission” includes approvals, authorisations, permissions, and consents;</li>
                    <li>(y) “Qualifying Incident” means an Incident caused by events other than as specified in the applicable Service Schedule;</li>
                    <li>(z) “Qualifying Service” means a type of Service that must be firstly subscribed by the Customer in order to qualify the Customer to subscribe for an additional Service which includes but is not limited to a type of Managed Service as identified in Service Schedule G, Service Schedule H or a type of value added service as specified in the applicable Service Schedule;</li>
                    <li>(aa) “Renewed Service Term” means the (i) period as stipulated in a new Service Order Form which the Customer has executed for renewal of the said Service, commencing on the day after the expiry of the Initial Service Term or Preceding Renewed Service Term, as the case may be; or (ii) period equal to the Initial Service Term or preceding Renewed Service Term, as the case may be, where the Customer does not and/or has not executed a Service Order Form for renewal of the said Service, commencing on the date after the expiry of the Initial Service Term or preceding Renewed Service Term, as the case may be, unless otherwise specified in the Service Order form or the Service Schedule;</li>
                    <li>(bb) “RFS’ed” or “RFS” identifies the status of a building that TIME has connected such building to the TIME Network and is now ready for the provision of the service to the occupants therein by TIME;</li>
                    <li>(cc) “SAT” means the appropriate Service acceptance test, performed to ensure that the Service is ready for Customer’s use, and “SAT Form” means either service acceptance form, work completion advice form or such other document by whatever name evidencing the same;</li>
                    <li>(dd) “SCD” means the Service commencement date;</li>
                    <li>(ee) “Service Equipment” means those equipment that is provided by TIME as part of the Standard Service Component as set out in in the applicable Service Schedule, other than CPEs (even if such CPE is provided by TIME);</li>
                    <li>(ff) “Service Location” means the location(s) or site(s) where the Service Equipment is to be installed for the Services to be provisioned and used by the Customer, as identified in the Service Order as service installation address;</li>
                    <li>(gg) “Service Order” or “Service Order Form” means a service order entered into between the Parties for a specific Service offered by Time and includes all applicable forms and terms;</li>
                    <li>(hh) “Service Schedule” means the applicable Service Schedule which contains special terms that govern and are specific to that service type subscribed by the Customer and as indicated or identified in the Service Order for the applicable Service;</li>
                    <li>(ii) “Service” means the service subscribed by the Customer as specified in the Service Order;</li>
                    <li>(jj) “SKMM” or “MCMC” means the Suruhanjaya Komunikasi dan Multimedia Malaysia (or in English the Malaysian Communications and Multimedia Commission), the communications industry regulator in Malaysia;</li>
                    <li>(kk) “SST” means either the sales tax imposed pursuant to the Malaysian Sales Tax Act 2018 (Act 806) (if applicable) and/or the service tax imposed pursuant to the Malaysian Service Tax Act 2018 (Act 807) (where applicable) (including any amendments thereof);</li>
                    <li>(ll) “Standard Service Components” has the meanings as set out in Service Schedule D or E for each type of service identified in the applicable rows;</li>
                    <li>(mm) “Standard Service Scope” has the meanings as set out in Service Schedule G or Service Schedule H for each type of Managed Service identified in the applicable rows;</li>
                    <li>(nn) “Termination Charges” means those costs, expenses and charges as identified in the Service Schedule applicable to a Service that is payable if that Service or Agreement is terminated after the SCD;</li>
                    <li>(oo) “Term” means the aggregate of the Initial Service Term, the Renewed Service Term and/or the period ending on the date of termination of the Service (as the case may be);</li>
                    <li>(pp) “TIME Network” means the communications network owned or leased by TIME and used to provide the Service;</li>
                    <li>(qq) “TIME POP” means a point of presence in a country which is either operated by TIME or by a third party provider or by an OLNO;</li>
                    <li>(rr) “TIME Team” means TIME’s employees, contractors or authorised third parties;</li>
                    <li>(ss) “TIME”, “our” or “we” refers to TT dotCom Sdn Bhd or the entity whose name appears in the footer of the Service Order (as the case may be);</li>
                    <li>(tt) “Total Service Minutes” means the total minutes of network availability in a month (being number of calendar days in a calendar month multiplied by 1440 minutes per day;</li>
                    <li>(uu) “Unavailable Time” means the period of time (expressed in minutes) during which a Qualifying Incident exists that the network is unavailable, as measured by TIME in accordance with the parameters set out in the applicable Service Schedule;</li>
                    <li>(vv) “Use” means the carrying out of the works (including any civil works) to install, provision and test each and every Standard Service Component and the Service, performing any emergency, remedial or preventive maintenance works to the Standard Service Components and/or the Service, placing, removing or recovering of Service Equipment, and such acts as are reasonably necessary for the performance by TIME of its obligations under this Service Schedule throughout the Term; and</li>
                    <li>(ww) “VAT” means value added tax.</li>
                </ul>
                <p><strong>13.2 Interpretation & Construction</strong></p>
                <ul className="list-disc pl-5 mt-2 space-y-1 text-sm">
                    <li>(a) Singular words include the plural and vice versa;</li>
                    <li>(b) No presumption will arise favouring or disfavouring any Party by virtue of the authorship of any provision of these terms or the applicable Service Schedule, and the usual meaning of words used shall be applied;</li>
                    <li>(c) Headings used in the General Terms, Service Schedules or the APS Schedule are for convenience only, and are to be ignored when construing the provisions of this Agreement.</li>
                    <li>(d) If you subscribe for different Services and each Service is either subject to its applicable Service Schedule or subject to different terms within the same applicable Service Schedule, then for the avoidance of doubt, each Service and its applicable Service Schedule or the terms within the applicable Service Schedule (as the case may be) are to be construed as being applicable to that Service only and not applicable to all Services.</li>
                    <li>(e) Order of Priority. To the extent that the provisions of the General Terms, the Service Order and a Service Schedule are inconsistent, to the extent possible such provisions will be interpreted so as to make them consistent, and if that is not possible, then the Service Schedule shall prevail over the applicable Service Order and the General Terms, and the General Terms shall prevail over the Service Order.</li>
                    <li>(f) References to any statute, rule, regulation, order, directive shall be construed as references to such statute, rule, regulation, order or directive as may be amended, re-enacted or as modified by any other statute, rule, regulation, order or directive.</li>
                    <li>(g) References to Clauses are to clauses herein, and references to Paragraphs are to paragraphs in a Service Schedule; reference to a document includes all amendments, supplements to, or replacements of, that document whether paper or electronic/digital, and reference to a “person” includes any individual person, firm, company, corporation, government, state or agency of a state or any association, trust or partnership (whether or not having a separate legal personality).</li>
                    <li>(h) The words "Ringgit Malaysia" and the symbol "RM" shall be construed as the lawful currency of Malaysia. If a currency other than Ringgit Malaysia is used, the words used to describe that foreign currency or the symbol used shall be construed as the lawful currency of that country.</li>
                    <li>(i) Reference to “Party” shall refer to either TIME or the Customer as applicable, and reference to “Parties” shall refer to TIME and the Customer collectively.</li>
                    <li>(j) For the avoidance of doubt, where any Service Schedule refers to a service order such reference shall be construed as referring to the relevant Service Order in respect of the Service.</li>
                    <li>(k) Reference to “business day” shall mean Monday to Friday excluding Saturday, Sunday or any public holidays in the state of Selangor Darul Ehsan in Malaysia.</li>
                </ul>
            </div>
          </section>

        </div>
      </div>
    </div>
    </>
  );
}
